import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — West Egg Wealth",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-cream flex flex-col">
      <Nav />

      <main className="flex-1 pt-32 pb-24">
        <div className="max-w-3xl mx-auto px-6 lg:px-10">
          <p
            className="font-body small-caps text-sm tracking-widest mb-4"
            style={{ color: "#B8960C" }}
          >
            Legal
          </p>
          <h1 className="font-display text-4xl lg:text-5xl text-charcoal mb-3">
            Privacy Policy
          </h1>
          <p className="font-body text-base text-charcoal-soft mb-12">
            Effective April 2026 &mdash; West Egg Wealth LLC
          </p>

          <hr className="border-warm-gray mb-12" />

          <div className="prose-section space-y-10 font-body text-lg text-charcoal-soft leading-relaxed">

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">1. Introduction</h2>
              <p>
                West Egg Wealth LLC (&ldquo;West Egg Wealth,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates the Aegis platform and the westwealth.com website. This Privacy Policy explains how we collect, use, store, and share information when you use our services. By accessing or using Aegis, you agree to the practices described here.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">2. Information We Collect</h2>
              <p className="mb-4">We collect information you provide directly and information generated by your use of the platform:</p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  { label: "Account information", desc: "Name, email address, organization, and password when you register." },
                  { label: "Financial and asset data", desc: "Asset descriptions, valuations, insurance policy details, and related documents you upload to Aegis." },
                  { label: "Usage data", desc: "Log data including IP address, browser type, pages visited, actions taken, and timestamps." },
                  { label: "Communications", desc: "Messages you send to our support team or via in-app feedback forms." },
                ].map(({ label, desc }) => (
                  <li key={label} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span><strong className="text-charcoal">{label}:</strong> {desc}</span>
                  </li>
                ))}
              </ul>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">3. How We Use Your Information</h2>
              <p className="mb-4">We use collected information to:</p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  "Provide, operate, and improve the Aegis platform",
                  "Process and display asset, insurance, and document data you submit",
                  "Send transactional emails (account confirmations, alerts, renewal reminders)",
                  "Respond to support requests and communicate with you about your account",
                  "Detect, investigate, and prevent fraudulent or unauthorized activity",
                  "Comply with applicable legal obligations",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4">We do not sell your personal information or use it for third-party advertising.</p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">4. Data Storage and Security</h2>
              <p className="mb-4">
                Your data is stored on cloud infrastructure in the United States. We implement administrative, technical, and physical safeguards designed to protect your information, including:
              </p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  "Encryption in transit (TLS) and at rest (AES-256)",
                  "Role-based access controls limiting employee access to customer data",
                  "Audit logging of all platform actions with timestamps and user attribution",
                  "Regular security reviews and vulnerability assessments",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4">
                No system is completely secure. We encourage you to use a strong, unique password and to notify us immediately at{" "}
                <a href="mailto:privacy@westwealth.com" className="text-charcoal underline underline-offset-2 hover:opacity-70 transition-opacity">
                  privacy@westwealth.com
                </a>{" "}
                if you suspect unauthorized access to your account.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">5. Cookies and Tracking</h2>
              <p className="mb-4">
                We use cookies and similar technologies to operate and improve the platform:
              </p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  { label: "Essential cookies", desc: "Required for authentication, session management, and platform functionality. These cannot be disabled." },
                  { label: "Analytics cookies", desc: "Help us understand how users navigate the platform so we can improve it. Data is aggregated and not linked to individuals." },
                  { label: "Preference cookies", desc: "Remember settings such as your selected view or notification preferences." },
                ].map(({ label, desc }) => (
                  <li key={label} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span><strong className="text-charcoal">{label}:</strong> {desc}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4">
                You may configure your browser to refuse cookies. Note that disabling essential cookies will impair platform functionality.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">6. Third-Party Service Providers</h2>
              <p className="mb-4">
                We work with carefully selected third-party vendors to deliver our services. These providers access your data only as necessary to perform services on our behalf and are contractually obligated to protect it. Categories of providers include:
              </p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  "Cloud infrastructure and hosting",
                  "Payment processing (we do not store full payment card details)",
                  "Email delivery and transactional messaging",
                  "AI document processing (policy PDF parsing)",
                  "Customer support tooling",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4">
                We do not share your data with third parties for their own marketing or commercial purposes.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">7. Data Retention</h2>
              <p>
                We retain your account and platform data for as long as your subscription is active and for a reasonable period thereafter to satisfy legal, tax, and contractual obligations. When you close your account, we will delete or anonymize your data within 90 days unless a longer retention period is required by law. Document uploads and exported reports are retained for the duration of your subscription.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">8. Your Rights</h2>
              <p className="mb-4">
                Depending on your jurisdiction, you may have the right to:
              </p>
              <ul className="list-none space-y-3 pl-0">
                {[
                  "Access a copy of the personal information we hold about you",
                  "Correct inaccurate or incomplete information",
                  "Request deletion of your personal information",
                  "Object to or restrict certain processing",
                  "Receive your data in a portable, machine-readable format",
                ].map((item) => (
                  <li key={item} className="flex gap-3">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "#B8960C" }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4">
                To exercise these rights, contact us at{" "}
                <a href="mailto:privacy@westwealth.com" className="text-charcoal underline underline-offset-2 hover:opacity-70 transition-opacity">
                  privacy@westwealth.com
                </a>
                . We will respond within 30 days.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">9. Changes to This Policy</h2>
              <p>
                We may update this Privacy Policy from time to time. When we make material changes, we will update the effective date at the top of this page and, where appropriate, notify you by email. Continued use of Aegis after changes take effect constitutes your acceptance of the revised policy.
              </p>
            </section>

            <section>
              <h2 className="font-display text-2xl text-charcoal mb-4">10. Contact Us</h2>
              <p>
                Questions, requests, or concerns about this Privacy Policy may be directed to:
              </p>
              <div className="mt-4 pl-6 border-l-2 border-warm-gray">
                <p className="text-charcoal font-medium">West Egg Wealth LLC</p>
                <p>
                  Email:{" "}
                  <a href="mailto:privacy@westwealth.com" className="text-charcoal underline underline-offset-2 hover:opacity-70 transition-opacity">
                    privacy@westwealth.com
                  </a>
                </p>
              </div>
            </section>

          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
